### ISSUE TITLE
Confluence in a docker, cool idea, ETA?

### ISSUE THREAD

**Issue by geekpete** [docker-atlassian/confluence#1]

**Comment by geekpete** [comment]
The reason I found this is because we use hosted confluence and we want an easy way to be able to spin up a local copy of a confluence export in the event that we're unable to access/use the hosted confluence. 

Docker would be perfect for this.

Pull down the containers, turn them on and load the backup into it, done.

**Comment by kdekooter** [comment]
:+1:
